### PR TITLE
Support bootstrap4

### PR DESCRIPTION
**Pull request by 44uk**
Add class for fragment and bootstrap4 style.

### CODE REVIEW

**Comment by 44uk** [comment]
Failing Travis CI by Rails 4.x on Ruby 1.9.3, what should I do for all green?

**Comment by MrShemek** [comment]
+1

**Comment by h6ah4i** [comment]
+1

I also need this feature for spectre.css. It has the same syntax with Bootstrap 4.

```html
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">
      Home
    </a>
  </li>
  <li class="breadcrumb-item">
    <a href="#">
      Profile
    </a>
  </li>
  <li class="breadcrumb-item">
    Change avatar
  </li>
</ul>
```

ref.) https://picturepan2.github.io/spectre/components.html#navigation

**Comment by 44uk** [comment]
What we really need may be supporting fragment class.

**Comment by czj** [comment]
Hi!

@WilHall as [Ruby 2.0 support has ended](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/) we should probably remove it from Travis CI. Could you please do that so @44uk 's tests can pass ?

@WilHall could you please merge it afterwards ? We love Gretel and being able to upgrade to Bootstrap 4 beta 1 with it would be appreciated 👍

**Comment by 44uk** [comment]
bootstrap v4.0.0-beta had been released. but no need to change.
https://getbootstrap.com/docs/4.0/components/breadcrumb/

**Comment by mkasztelnik** [comment]
@44uk since this repo is not maintained anymore can you submit this PR into https://github.com/WilHall/gretel (soon-to-be) active fork?

**Comment by 44uk** [comment]
@mkasztelnik Thank you for the advice. I'll check updated bootstrap(Currently v4.1.3 released) and do PR to the fork.

**Comment by czj** [comment]
@mkasztelnik thank you for your work.

Will https://github.com/WilHall/gretel be the repo from which the gem is built from now on ?

**Comment by MrShemek** [comment]
@czj yes, together with @WilHall we are going to maintain the gem again.

**Comment by czj** [comment]
Awesome @MrShemek :-) We'll gladly help if we can @levups

**Pull request closed without merging**
