### PR TITLE
Option to prevent linking of last crumb to current url

### PR DESCRIPTION
**Pull request by brendon**
Enhanced contribution instructions

### CODE REVIEW

**Comment by shaneog** [comment]
Is there any reason why this PR was not merged?

**Comment by alaouy** [comment]
THIS ! should be merged !

**Comment by brendon** [comment]
Who knows?! :) `gretel` is still great though!

**Comment by lassebunk** [comment]
Sorry guys. Haven't been so active Rails-wise lately. Not forgotten though. I will merge when I get the time.

**Comment by Andreaz01** [comment]
Please, merge this PR. Needed!

**Comment by WilHall** [comment]
Moving work on this feature to [feature/last-crumb-link](https://github.com/lassebunk/gretel/tree/feature/last-crumb-link).

**Comment by brendon** [comment]
Thanks @WilHall, good to see some progress on it :)

**Pull request closed without merging**
